### PR TITLE
Add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by rffontenelle**

### CODE REVIEW

**Comment by rascarlo** [comment]
Hi @rffontenelle and thanks for such pull request. Will you keep the strings up to date if any changes will occur? Before adding brazilian portuguese localisation, I would like to be sure such thing won't soon be abandoned. Thanks again and forgive my late reply

**Comment by rffontenelle** [comment]
@rascarlo Sure, no problem. I already have the values/strings.xml watched by a page monitor extension. Nevertheless, consider using a translation platform more translator-friendly like Weblate (which is gratis for free software), as such platforms notify the translator.

**Comment by rffontenelle** [comment]
Any news regarding merging this PR and rascarlo/AURdroid#19 ?

**Comment by rascarlo** [comment]
thank you @rffontenelle

**Review by Scratch-S — APPROVED** [review]

**Review by Scratch-S — APPROVED** [review]
12c76b9dffc2132c9f3897ecae75f292e8d37418

**Pull request merged**
